#!/usr/bin/env sh

for cmd in inotifywait rsync perl; do
  if ! [ -x "$(command -v $cmd)" ]; then
    echo "error: $cmd is not installed" >&2
    exit 1
  fi
done

set -e
trap 'clean; exit' SIGINT

clean() {
    echo "Cleaning up..." >&2
    rm dist
    rm $SITE_DIR/*.hot-update.*
}

source "$(dirname "$0")/config"
PATH="$PATH:./node_modules/.bin"

if ! [ -f ./package.json ]; then
  echo "Current working directory is not the root of the project" >&2
  exit
fi

ln -s "$SITE_DIR" dist
BROWSER=none react-scripts start &

while true; do
  echo watching $SITE_DIR
  inotifywait -re close_write public
  rsync -av --update public/. "$SITE_DIR"
done

